name: setup-nu

runs:
  using: composite
  steps:
    - name: setup nu
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail

        version=0.113.1

        case "${RUNNER_OS}-${RUNNER_ARCH}" in
          "Linux-X64")
            platform="x86_64-unknown-linux-gnu"
            ;;
          "Linux-ARM64")
            platform="aarch64-unknown-linux-gnu"
            ;;
          "macOS-X64")
            platform="x86_64-apple-darwin"
            ;;
          "macOS-ARM64")
            platform="aarch64-apple-darwin"
            ;;
          "Linux-RISCV64")
            platform="riscv64gc-unknown-linux-gnu"
            ;;
          *)
            echo "${RUNNER_OS}-${RUNNER_ARCH} is not supported"
            exit 1
            ;;
        esac

        mkdir -p ~/.nushell
        gh -R nushell/nushell release download "$version" -p "*-${platform}.tar.gz" -O - \
        | tar xvz -C ~/.nushell --strip-components=1
        echo "$HOME/.nushell" >> "$GITHUB_PATH"
